---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: cassandra-data
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    nfs:
      path: /mnt/wildfly-swarm/cassandra-data
      server: 10.19.137.41
    persistentVolumeReclaimPolicy: Recycle

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: cassandra-logs
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    nfs:
      path: /mnt/wildfly-swarm/cassandra-logs
      server: 10.19.137.41
    persistentVolumeReclaimPolicy: Recycle
