spring:
  application:
    name: presentation
  zipkin:
    baseUrl: http://zipkin/
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8080

zuul:
  ribbon:
    listOfServers: zuul:8080

hystrix.command.PricingCall.execution.isolation.thread.timeoutInMilliseconds: 2000

hystrix:
  threadpool:
    SalesThreads:
      coreSize: 20
      maxQueueSize: 200
      queueSizeRejectionThreshold: 200